# ÏóêÎîîÌÑ∞ÏóêÏÑú regex Í≤ÄÏÉâÏúºÎ°ú replace ÌïòÍ∏∞ (** ** ‚Üí <mark></mark>)
# \*\*(.*?)\*\*
# <mark>$1</mark>

# ÏóêÎîîÌÑ∞ÏóêÏÑú regex Í≤ÄÏÉâÏúºÎ°ú replace ÌïòÍ∏∞ (<mark></mark> ‚Üí ** **)
# <mark>(.*?)<\/mark>
# **$1**

# Site
repository: dev-loggi/dev-loggi.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Seongrok, Cho
title: Android Developer
email: jsl663663@gmail.com
website: github.com/dev-loggi

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: dev-loggi
# youtube_username: user-pk6no1ub6p
# twitter_username: facespics
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: Blog
    icon: fas fa-blog
    url: https://jsl663.tistory.com
  - title: YouTube Link
    icon: fab fa-youtube
    url: https://www.youtube.com/channel/UCYPnZS7wsGgdaCM1GYAaKrg

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  Hello, I'm Android developer Seongrok Cho with a keen interest in design.<br/><br/>
  
  Since my undergraduate years when I developed [Windows games](https://youtu.be/vx7aT_5YpIA) using C#, I have shown a strong passion for design and developed a deep understanding of **UI/UX and design trends**.<br/>
  This interest has continued into app development, where I've gained **proficiency in Android's view system**. I've consistently improved my **UI development skills** by delving into various aspects, such as CustomView utilization, animation and transitions, user touch interactions, and the modularization of common design systems.<br/><br/>
  
  I have also put in continuous efforts to enhance my **programming skills and development capabilities**.<br/>
  During a 6-month internship at an IT company, I gained valuable **experience in app development and deployment**. Subsequently, I have been involved in ongoing project development, elevating my proficiency and comprehension of **cutting-edge technology stacks**, including design patterns, clean architecture, and Jetpack libraries.<br/><br/>
  
  In recent times, I had the opportunity to take on the role of a **technical team leader** in a team project. This involved system design and providing technical support to the team, broadening my perspective on development even further.

content:
  # Experience
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Pangaea Solution
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Android Developer (Intern)
        caption: 03/2017 - 08/2017
        additional_links:
          - title: Google Play Link
            icon: fab fa-google-play
            url: https://play.google.com/store/apps/details?id=com.goalgetter.goalgetterapp
        quote: >
          Development of the Social Goal Diary 'GoalGetter' SNS Mobile App Service
        description: |
          __`Android` `Java`__
          - Development and testing of the initial 1.0 version of the service, incorporating client feedback, and deployment tasks.
          - Development of a total of 23 screens and functionalities, including member profiles, posts, messaging, and advertising features.
          - Implementation of ConstraintLayout and RecyclerView.
          - Enhancement of messenger performance utilizing SQLite.
          
          [See More about Development](https://dev-loggi.notion.site/GoalGetter-d3a18b465fad46519bf5f29e45e6c904?pvs=4)

  # Education
  - title: Education
    layout: list
    content:
      - layout: left
        title: KT AIVLE School 3rd Gen.
        caption: 02/2023 - 07/2023
        sub_title: KT
        link: https://aivle.kt.co.kr/
        description: |
          - Practical AI developer training for the industry
          - Theory and practical experience in data analysis, machine learning, and deep learning (Computer Vision, Natural Language Processing) for AI modeling
          - Theory and practice of MLOps, Front-End, Back-End, and AWS Cloud for AI service development
          - Completion of mini-projects for hands-on experience in each subject's curriculum
          - üèÜ Awarded for the major project: "FuniBuni" an AI-based waste disposal app for convenient disposal of large household items
      - layout: left
        title: SW Algorithm Course
        caption: 07/2022 - 08/2023
        sub_title: Samsung Electronics
        description: |
          - Theoretical lectures on software data structures and algorithms, along with practical problem-solving sessions
          - Design and implementation of data structures suitable for given problems
          - Attainment of SW Expert Academy - Professional (Level B)

  # Projects
  - title: Projects
    layout: list
    content:
      # ÌçºÎãàÎ≤ÑÎãà
      - layout: left
        title: FuniBuni
        caption: 06/2023 - 07/2023
        sub_title: Tech Lead, Android
        additional_links:
          - title: Github Link
            icon: fab fa-github
            url: https://github.com/KT-AIVLE-3rd-AI-Team10/funibuni-fe-android
          - title: YouTube Link
            icon: fab fa-youtube
            url: https://youtu.be/N-wBxebZWTY
        quote: >
          AI-Based Convenient Disposal App for Large Household Waste
        description: |
          __`Android` `Kotlin` `MVVM` `Clean Architecture`__
          - KT AIVLE School 6-member team project (Excellent AwardüèÜ)
          - Performance of <mark>the role of Technical Team Leader</mark>, including AI model design, system architecture, ERD, API design, testing, and server setup
          - Utilized <mark>Coroutines & Flow</mark> for asynchronous programming and <mark>UiState management</mark>
          - Implemented touch animation effects, custom dialogs, and <mark>modularization of a common Design System</mark>
      # ÎèôÏòÅÏÉÅ Ctrl+F
      - layout: left
        title: Video CtrlÔºãF
        caption: 04/2023 - 06/2023
        sub_title: Tech Lead, Frontend
        additional_links:
          - title: Github Link
            icon: fab fa-github
            url: https://github.com/Video-CtrlF/video-ctrlf-introduce
          - title: YouTube Link
            icon: fab fa-youtube
            url: https://youtu.be/UvRD_n5bfaQ
        quote: >
          AI-Based Text Search Service in YouTube Videos (Chrome Extensions)
        description: |
          __`HTML` `CSS` `JavaScript`__
          - K-Digital Training Hackathon 5-member team project (Passed the preliminary round)
          - Implemented text search functionality (Ctrl+F) and screen rendering for YouTube videos
          - Solved Single Page Application (SPA) and Cross-Origin Resource Sharing (CORS) issues
          - Drastically reduced AI model inference time using the SSIM image similarity algorithm
          - Implemented an algorithm to prevent continuous duplicate text in each frame
      # Î≠êÎçîÎùº
      - layout: left
        title: Mwodeola (means, What is it?)
        caption: 11/2021 - 03/2022
        sub_title: Android, Backend
        additional_links:
          - title: Github Link
            icon: fab fa-github
            url: https://github.com/dev-loggi/mwodeola-android
          - title: YouTube Link
            icon: fab fa-youtube
            url: https://youtu.be/JI3wjMUU__s
        quote: >
          Android App for Managing Website and App Account ID/Password Records
        description: |
          __`Android` `Kotlin` `MVP`__
          - Solo project for app development, including planning, design, security, app and server development
          - Developed features such as user registration, account ID/password storage, app screen locking, dual-lock authentication for account password confirmation, and automatic login completion service using Android's Autofill framework
          - Implemented separate logic and database design for multiple accounts and accounts registered with social media IDs
          - Enhanced UI/UX by using thumbnail icons for each account and [developing a CustomIconView](https://jsl663.tistory.com/43)
          - Improved design quality by utilizing various [custom views and animation/transitions](https://jsl663.tistory.com/49).

  # Side Projects
  - title: Side Projects
    layout: list
    content:
      # Ïπ¥Ïπ¥Ïò§Î≤ÑÏä§ ÌÅ¥Î°† Ïï±
      - layout: left
        title: KakaoBus Clone App
        caption: 09/2019 - 11/2019
        sub_title: Android
        #        link: https://github.com/dev-loggi/kakaobus-clone
        #        link_text: Github Link
        additional_links:
          - title: Github Link
            icon: fab fa-github
            url: https://github.com/dev-loggi/kakaobus-clone
          - title: YouTube Link
            icon: fab fa-youtube
            url: https://youtu.be/mzymEDLK_8I
        quote: >
          Attempting to Implement Certain Functions and Screens of the KakaoBus App as Closely as Possible
        description: |
          __`Android` `Kotlin` `MVP`__
          - Integration of "Bus Stop and Bus Arrival Information API" from the Public Data Portal.
          - Implementation of bus stop search, bus route and real-time arrival information by bus stop, bus route and stop favorites, and boarding notification features.
          - Implementation of a **timer** that updates estimated arrival times for each bus route **in real-time, every second**.
      # WATCHA ÌÅ¥Î°† Ïï±
      - layout: left
        title: WATCHA Clone App
        caption: 2019.02 - 2019.04
        sub_title: Android
        #        link: https://github.com/dev-loggi/watcha-clone
        #        link_text: Github Link
        additional_links:
          - title: Github Link
            icon: fab fa-github
            url: https://github.com/dev-loggi/watcha-clone
          - title: YouTube Link
            icon: fab fa-youtube
            url: https://youtu.be/lfmCE_RQ7pY
        quote: >
          Attempting to Mimic Certain Features and Screens of the WATCHA Movie OTT Service App as Closely as Possible
        description: |
          __`Android` `Kotlin` `MVP`__
          - Implementation of main screen, movie search, movie details, rating submission, and video player functionalities.
          - Implementation of Animation & Transition effects.
          - Utilization of the **ExoPlayer** library for the video player and implementation of **touch interface features**.
  

  # Skills
  - title: Skills
    layout: list
    content:
      - layout: left
        title: Android
        sub_title: (Intermediate)
        description: |
          - Kotlin, Java
          - Multi Module, Clean Architecture, Repository Pattern, MVVM, MVP
          - Jetpack AAC (ViewModel, LiveData, DataBinding, Lifecycles, Navigation)
          - Dagger Hilt
          - Retrofit2, Okhttp3, Coroutines, Flow
          - Room, Datastore
          - CustomView, Animator, LayoutTransition, MotionLayout, Material Design 3
      - layout: left
        title: Backend
        sub_title: (Classroom Study)
        description: |
          - AWS EC2, S3
          - NGINX, uWSGI
          - Django, Python
          - REST API, JWT
      - layout: left
        title: AI
        sub_title: (Classroom Study)
        description: |
          - Python, Jupyter Notebook
          - numpy, pandas, matplotlib, seaborn
          - Scikit-learn, Keras, Tensorflow
          - ML, DL(NLP, CV)
      - layout: left
        title: Frontend
        sub_title: (Beginner)
        description: |
          - HTML, CSS, JavaScript
          - Chrome Extensions

  # Certificates
  - title: Certificates
    layout: list
    content:
      - layout: left
        title: AICE (Associate)
        sub_title: KT Corporation and The Korea Economic Daily, Jointly
        caption: 04/21/2023
        link: https://aice.study/
        description: |
          - AICE (AI Certificate for Everyone) Artificial Intelligence Utilization Competency Certification.
          - Competencies in data analysis, data preprocessing, machine learning/deep learning modeling, and model performance evaluation.
          - Skills in Scikit-learn and Tensorflow.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
